### ISSUE TITLE
Use class for styling

### ISSUE THREAD

**Issue by cyouh95** [MegRenae/prj-rev-bwfs-dasmoto#2]
It is generally suggested to avoid inline styling of elements. Instead, you could add a class to each of these `span` elements and use that as the selector to style your elements.

HTML:
```html
<span class="price" >Starting at $3.00 / brush.</span>
```

CSS:
```css
.price {
  font-weight: bold; 
  color: blue;
}
```

https://github.com/MegRenae/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L16
